name: VoltskiyaMobSystem
version: 1.0
main: voltskiya.mob.system.VoltskiyaMobPlugin
api-version: 1.19
authors: [ appleptr16 ]
softdepend: [ LoadDependencies, VoltPluginManager, AppleMCUtil, DecodingNms, VoltskiyaUtilities,VoltskiyaWebserver, WorldGuard ]
